sudo: required
language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xvfb
install:
  - sudo -H pip install selenium
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=webtest
  matrix:
    - OCAML_VERSION=4.01
    - OCAML_VERSION=4.02
